### ISSUE TITLE
Merging Loom Files

### ISSUE THREAD

**Issue by dylanmr** [velocyto-team/velocyto.R#10]
Hi, 

I recently got the CLI interface to work quite well with my 10x samples. However, I was unable to get the CLI run10x command to run on all 10x samples at once. I received this error: 

IndexError: list index out of range

Therefore I went ahead and generated separate Loom Files for each of my samples. Is there any way in R (or python) that you would recommend to merge the loom files from each sample so I can work with all samples at once? 

Dylan

**Comment by pkharchenko** [comment]
You can just merge the matrices from different loom files … for instance, for the spliced (emat) count matrices:

emat1 <- ldat1$spliced;
emat2 <- ldat2$spliced;
emat <- cbind(emat1, emat2);


Same thing for the $unspliced matrices. Obviously for many files you’d do this in a loop.
Best,
-peter.

**Comment by dylanmr** [comment]
Great! Thanks!
