### ISSUE TITLE
pca.velocity.plot works, but show.velocity.on.embedding.cor fails with OpenMP error

### ISSUE THREAD

**Issue by blin100** [velocyto-team/velocyto.R#131]
Hi all, I'm running the most recent version of velocyto.R, on a cluster, and I'm running into a very confusing problem. Running through the trial datasets, I can get decent plots using pca.velocity.plot, but whenever I try to use it on any other embedding, using show.velocity.on.embedding.cor, I get a stream of
`OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.`
This ends with a segmentation fault and R crashes.

I've attempted to fix this using a clean conda2 environment, 4.2.13, and using python 3.6.0
There was a fix found elsewhere for CONCOCT, to install a specific blas version using this command:
`conda install blas=2.5=mkl`

But this was unable to help.
Has anyone run into this before and have a fix, or any suggestions??

Thanks very much!

**Comment by blin100** [comment]
nevermind, fixed this issue: found out I hadn't filtered out low quality cells, since I was using the seurat wrapper and following their short vignette, but didn't realize theirs had previously been filtered.

**Comment by lixin4306ren** [comment]
Hi, @blin100 

I got the same issue regarding openblas. You meant this error was caused by low-quality cells? How do you filter out them before running `show.velocity.on.embedding.cor`? Thanks.

Xin

**Comment by blin100** [comment]
Hi Xin, yes I believe it was low-quality cells that did this. I think adding in a line: 

`pulse_seq<-subset(pulse_seq, subset=nCount_spliced> 2000)
`
is sufficient, however just for my own sanity, I ended up doing an entire Seurat processing run to double check everything was ok. Before the filtering, there was an extra massive cluster of bad cells, after this filtering, it was gone.

```

import("/media/sf_ubuntu_share/data/Tp0_Rep3_Tom.matrices.rds")->file
pulse_seq <- as.Seurat(x = file)
CreateSeuratObject(file$exon, project = "Tp0_Rep3", assay = "spliced")->pulse_seq
pulse_seq[["unspliced"]] <- CreateAssayObject( counts = file$intron )
pulse_seq[["ambiguous"]] <- CreateAssayObject( counts = file$spanning )
pulse_seq<-subset(pulse_seq, subset=nCount_spliced> 2000)
VlnPlot(pulse_seq, features=c("nCount_spliced","nCount_unspliced","nCount_spanning"))

pulse_seq <- SCTransform(object = pulse_seq, assay = "spliced")
pulse_seq <- RunPCA(object = pulse_seq, verbose = FALSE)
pulse_seq <- FindNeighbors(object = pulse_seq, dims = 1:20)
pulse_seq <- FindClusters(object = pulse_seq)
pulse_seq <- RunUMAP(object = pulse_seq, dims = 1:20)
DimPlot(pulse_seq, reduction = "umap")
pulse_seq <- RunVelocity(object = pulse_seq, ambiguous = "ambiguous", deltaT = 1, kCells = 50, fit.quantile = 0.02, ncores= 4)
```

**Comment by lixin4306ren** [comment]
Thanks a lot. I will give it a try.

**Comment by ps120195** [comment]
I am facing the same issue .
![runvelocityerror](https://user-images.githubusercontent.com/62909237/118957209-f35de680-b97d-11eb-9460-b3d8d612b416.png)
I followed the filtering step suggested above but nothing worked.
Rebuidling the library with USE_OPENMP=1 also didnt solve this problem.
Help needed.

**Comment by qingzengLi** [comment]
I am facing the same issue .
I execute my command on the server，when i add an parameter `n.cores = 1` for `show .velocity.on.embedding.cor()`.The error disappeared

**Comment by xin-bang** [comment]
> I am facing the same issue . I execute my command on the server，when i add an parameter `n.cores = 1` for `show .velocity.on.embedding.cor()`.The error disappeared

cool~
