### ISSUE TITLE
nonobvious error message

### ISSUE THREAD

**Issue by mahogny** [velocyto-team/velocyto.R#14]
hi! I am running this code:
==============
library(velocyto.R)
path <- "./fastq/STAR/"
files <- system(paste('find',path,'-name "*sorted.bam" -print'),intern=T)
print(files)
names(files) <- gsub(".*\\/(.*).sorted.bam","\\1",files)
dat <- read.smartseq2.bams(files,"mm10.refFlat",n.cores=20)
saveRDS(dat,"velo.RData")

===================

and I get:

reading gene annotation ... done ( 40147 genes)
parsing exon information ... done
reading in 32 bam files ... done
estimating gene counts ... done
adjusting gene annotation based on expressed regions ... Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric
Calls: read.smartseq2.bams -> <Anonymous> -> <Anonymous> -> <Anonymous>
In addition: Warning messages:
1: In parallel::mclapply(bam.files, t.annotate.bam.reads, genes = genes,  :
  scheduled cores 13, 8, 12, 17, 7, 19 encountered errors in user code, all values of the jobs will be affected
2: In parallel::mclapply(cdl, t.get.estimates2, genes = genes, mc.cores = n.cores) :
  scheduled cores 17, 13, 12, 8, 7, 19 encountered errors in user code, all values of the jobs will be affected
3: In parallel::mclapply(cdl, function(x) { :
  scheduled cores 13, 12, 8, 7, 19, 17 encountered errors in user code, all values of the jobs will be affected
Execution halted

what might this mean?

**Comment by pkharchenko** [comment]
It's hard to tell what's causing this. Can you show traceback() output please. Perhaps it breaks on a single file as well and you could share a minimal example to reproduce the error.
Thanks,
-peter.

**Comment by abhaduri** [comment]
I had a similar error! In my case, reducing the number of bam files inputted at a time solved the problem. With about 512 GB of RAM on my machine, I could inload up to to about 5.5-6GB of bam files at a time without causing the error. In the event I exceeded that, I would get the same error you are seeing.

**Comment by pkharchenko** [comment]
The new version deprecates read.smartseq2.bams() and allows for uniform annotation of smart-seq2 bams using velocyto.py command line. This will produce a loom file that can be read in on the R side. The chromaffin smart-seq2 tutorial has been modified to show  therelevant commands.
