### ISSUE TITLE
does velocyto work with transcriptome reference?

### ISSUE THREAD

**Issue by xuesoso** [velocyto-team/velocyto.R#145]
Hi, thanks for developing & maintaining this tool. I want to ask if it's possible to use Velocyto when your sample is aligned to transcriptome reference? We have a transcriptome reference generated from cDNA which doesn't really contain intronic sequences, thus I suspect that reads mapping mostly to the intronic region will be dropped out. If I generate an annotation gtf with predicted splice junctions (i.e. split the transcripts into exons based on splice junction prediction), have you or others had experience how Velocyto performs? Is there any unexpected issues that may appear? Thanks in advance!

**Comment by pkharchenko** [comment]
That wouldn’t be possible - the estimates very much rely on the intronic read alignment.
