### ISSUE TITLE
Generating a refFlat from gtf (human annotation)

### ISSUE THREAD

**Issue by rosshandler** [velocyto-team/velocyto.R#18]
Dear Velocyto team,

 I was wondering if you have a tool or a command line to generate refFlat from gtf. I used this tool called gtfToGenePred, but I was not able to create the right file for using function read.smartseq2.bams()
  Here is my very simple command line:

gtfToGenePred gencode.v27.chr_patch_hapl_scaff.annotation.gtf h38.genes.refFlat

Please can you let me know what is the right way of creating refFlat files? Great tool is velocyto btw.

Thank you! 
Ivan

**Comment by pkharchenko** [comment]
Dear All,
 We’ll be switching smart-seq2 annotation to a common python pipeline soon. It’s not quite there yet, but that should allow to use gtf files directly. 
Best,
-peter.

**Comment by rosshandler** [comment]
Thank you both @dcroote and @pkharchenko. Problem solved. 

Best,
-Ivan

**Comment by pkharchenko** [comment]
Closing the issue, as it's been resolved. Also note, the updated version deprecates read.smartseq2.bams and recommends using updated velocyto.py to annotate reads and produce a loom file that can be read in on the R side. The chromaffin example has been updated to show relevant commands.
