### ISSUE TITLE
No reads returned by read.smartseq2.bams

### ISSUE THREAD

**Issue by pdexheimer** [velocyto-team/velocyto.R#20]
Hi VeloCytoers -

I've been trying to use this tool by following the Chromaffin tutorial with my own data.  Unfortunately, I'm stumbling on the very first QC measure.  The histogram of reads per gene in the tutorial consists of a single bar around zero reads for me.  Examining the list returned by read.smartseq2.bams, it appears that nearly all of the data matrices are empty (`emat`, `iomat`, `smat`, `base.df$el` are all empty, but `base.df$il`, `exons`, and `genes` are not).

After debugging for a while, I think I've found the root problem.  The `cdl` variable constructed on line 1424 of momentum_routines.R is always a list of NULLs, which I think is because `t.annotate.bam.reads` has no return result.  Changing line 1572 in that function from

```
x <- do.call(rbind,lapply(chrl,function(chr) {
```

to

```
do.call(rbind,lapply(chrl,function(chr) {
```

seems to solve it for me, at least as far as I can determine by semi-manually stepping through the code in read.smartseq2.bams.

Happy to submit a PR to this effect (or not), but I wonder about this.  From what I can tell, this function has never returned a value - which makes my explanation seem a little suspect.  Any thoughts/comments?

**Comment by pdexheimer** [comment]
It looks like my initial analysis was wrong - I tested by running `lapply` rather than `mclapply`.  Implementing my proposed change doesn't actually change the root of the problem, that the `cdl` list contains only NULLs.  Will keep working on it...

**Comment by pdexheimer** [comment]
Turns out to have been a data issue of some kind - my subset of 100 cells was apparently too large for my available memory.  Trimming to a more restricted subset of 46 cells successfully loaded, I suppose that I had a silent "out of memory" error

**Comment by pkharchenko** [comment]
We have recently updated the way Smart-seq2 data is pre-processed. All protocols are now pre-processed in a more uniform manner, using velocyto.py to produce loom file. 
Please refer to the updated Chromaffin Smart-seq2 notebook for an example.
Thanks!
