### ISSUE TITLE
Velocyto in transition of aged single cell

### ISSUE THREAD

**Issue by terooatt** [velocyto-team/velocyto.R#27]
Can velocyto be used to determine transition of cells during longer period of time such as aging? I have generated several aged mouse tissue samples from 8 weeks to 64 weeks old, I used velocyto on these and see very nice results yet I am not clear whether this package is appropriate for that kind of analysis since on the paper it is described for analysis of short timescale data. 
"We show that RNA velocity is a vector that predicts the future state of individual cells on a timescale of hours"

Of course I am also using pseudo time analysis such as monocle2 and other package but the combination of SWNE and velocyto gives me very interesting results.  I just wonder if it is appropriate to use jn this situation. 

Many thanks,
Tommy

**Comment by pkharchenko** [comment]
I am afraid that is unlikely to work. I would expect equilibration between spliced and unspliced molecules to proceed much faster than the timescales you’re considering, so the signal would not be apparent.
Best,
-peter.
