### ISSUE TITLE
Samples without UMI

### ISSUE THREAD

**Issue by mliiv** [velocyto-team/velocyto.R#4]
Will using C1 data from SMARTer protocol that has not UMIs incorporated also be possible?
I have run the source code from bam files line by line, setting min.umi.reads=0 but atm my final matrices (emat, iomat and smat) only have 1 row which is not correct, I think:

> str(emat)
Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:924764] 14 114 116 118 119 195 242 266 269 285 ...
  ..@ p       : int [1:97] 0 13459 28033 35010 41997 57568 72667 87057 92810 107753 ...
  ..@ Dim     : int [1:2] 196520 96
  ..@ Dimnames:List of 2
  .. ..$ : chr [1:196520] "ENST00000361727.3" "ENST00000539563.1" "ENST00000376104.2" "ENST00000543673.1" ...
  .. ..$ : chr [1:96] "1_c11_1-639_cntr" "1_c14_2-0015_cntr" "1_c59_0-7925_HS" "1_small_c62_0-788_HS" ...
  ..@ x       : num [1:924764] 1 7 7 7 4 15 40 25 13 183 ...
  ..@ factors : list()

I kept other parameters as default. Is there anything special to do for this data?

Thank you in advance.

**Comment by pkharchenko** [comment]
The matrix looks OK (it’s represented as a sparse matrix using dgCMatrix class), however, I don’t think velocity estimations will work reliably on such a small dataset. Also, C1 data tends to be quite noisy and we’ve never tested the approach on that.
-peter.

**Comment by mliiv** [comment]
Hi Peter,

thanks for your fast reply!
I did figure out that matrix was ok, had a thing with rowSums (default vs Matrix package) so I was able to calculate PCA from my small dataset (does not look too bad but I have only 1 cell type with control and treatment). However, I am still missing some relevant genes, so double-checking the expr.exons generation atm. I am using ensembl identifiers. 

I do have another Q - what about the details for using bulk RNA-seq data as input. Would you have that? Should I approach same way as STRTseq data - using bam files as input and starting from there?

Thanks again,
Maria

**Comment by pkharchenko** [comment]
Yes, you can read in bulk bam files using the same scripts as shown for smart-seq2 example.
Best,
-peter.

**Comment by mliiv** [comment]
Ok, thanks, I will try that.

But I still have a problem with my counted reads for my C1 data. I have a gene which is responding to my treatment, and I can visualize the reads – seeing that they are abundant in each exon. Nevertheless, I don’t have any counts for these transcripts in the final tl vector. I have been checking, and it’s also actually missing in the cdl for cells where I see expression. Do you know if the reduce.umi function might be somehow losing my reads here? Even though the param is set to 0, min.umi.reads=0 ?

Thanks!
Maria

**Comment by mliiv** [comment]
Hi again,

I still have a problem with my counted reads from my C1 data. I have a gene which is responding to my treatment, I visualize the reads – seeing that they are abundant in each exon. Nevertheless, I don’t have any counts for these transcripts in the final tl vector (nor the dat$emat). I have been checking, and it’s also actually missing in the cdl for cells where I see expression. Do you know if the reduce.umi function might be somehow losing my reads here? Even though the param is set to 0, min.umi.reads=0 ? 
I am looking for the gene so: grep("ENST00000453788.2", rownames(dat$emat)). This gives me the correct row number with which I can get the values in all cells. I have also confirmed that all exons for that gene are in the exons matrix.

Thank you,
Maria

**Comment by pkharchenko** [comment]
Can you please show the code you're using to read in the bam files. 
Thanks,
-peter.

**Comment by mliiv** [comment]
I am doing this:
min.umi.reads=0
min.exon.count=100
dat <- read.strtc1.bams(files,"genes.refFlat2", n.cores=28)

Could I be more specific somehow?

**Comment by pkharchenko** [comment]
Oh, you’re using wrong function. This one is for STRT/C1, which is a UMI-based protocol. I am surprised you found it - it’s not documented anywhere.
You should use smart-seq2 function read.smartseq2.bams(). See the following tutorial:
http://pklab.med.harvard.edu/velocyto/notebooks/R/chromaffin.nb.html <http://pklab.med.harvard.edu/velocyto/notebooks/R/chromaffin.nb.html>

If you find that expression of some key genes is still missing, please check the annotation refFlat annotation file. Are those genes being overlapped by other transcripts? If there are still discrepancies, then there might be some issue. 
Best,
-peter.

**Comment by mliiv** [comment]
Hi Peter,

ok, I tried with the smartseq2 function, same refFlat file - same problem persists. As I said before, my exon matrix seems to be correct and this gene does not have other coding transcripts running through on the opposite strand. If you want to check, it the HSPA8 locus on hg19. 
A quick fix might be, if there is a hidden problem with my file, if you would have a refFlat file for hg19?

Thanks,
Maria

**Comment by mliiv** [comment]
Hi again,
I am using transcript IDs (ENST) not gene IDs (ENSG) so that might bring in quite some redundancy, actually. Could that be an issue?
-Maria

**Comment by pkharchenko** [comment]
Yes, likely, as the read counting procedure would drop reads that can be assigned to more than one entry.

-peter.

**Comment by mliiv** [comment]
I see. I think I figured it out, too - the file is parsed sequentially so my first transcript from the gene gets most of the counts, then second  has a smaller number, and then third -> last have none.
But how do you deal with transcript isoforms, you don't think they matter here?

**Comment by pkharchenko** [comment]
The current approach doesn't take splice isoforms into account. It would be a good thing to do if we could somehow get a confident isoform-specific assignment of both spliced and unspliced reads.

-peter.

**Comment by mliiv** [comment]
Thanks, I got my C1 data read in. 
How about the bulk data - how many replicates are necessary? I see in the circadian paper (SRA025656 dataset you were using) that the is only 1 rep per condition. How to set the parameters for such data? Should I run gene.relative.velocity.estimates with kCells=1 ? Any other parameter differences?
-Maria

**Comment by mliiv** [comment]
Thanks, I got my C1 data read in.
How about the bulk data - how many replicates are necessary? I see in the circadian paper (SRA025656 dataset you were using) that the is only 1 rep per condition. How to set the parameters for such data? Should I run gene.relative.velocity.estimates with kCells=1 ? Any other parameter differences?
-Maria
