### ISSUE TITLE
Installing velocyto.R in Windows environment

### ISSUE THREAD

**Issue by jgarces02** [velocyto-team/velocyto.R#40]
Hi @velocyto-team, 

In the requirements for velocyto.R it appears UNIX as operating system for this package, is there any possibility of installing it in a Windows environment?

Thanks in advance.

**Comment by pkharchenko** [comment]
We haven’t tried, to be honest. If you have experience with Windows R environment, we would appreciate advice.
Thanks,
-peter.

**Comment by jgarces02** [comment]
Thanks for the quick response. I finally moved to a unix environment (I fear my windows knowledge is very basic user-level to hack your wonderful package).

**Comment by cswoboda** [comment]
Wanted to ask how easy it would be to create a Unix environment on a windows PC to use this package, I really want to add it to some of my Seurat data but have been unable to successfully download it. I've tried dicker already but have been unsuccessful

**Comment by jgarces02** [comment]
Hi @cswoboda. I don't know really, but new versions of Windows (from Windows 10 I think) include a "unix environment" called Windows Subsystem for Linux ([WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux)) that maybe can help you with this problem.
Luck!

**Comment by Enolia** [comment]
I installed velocyto.R using Ubuntu on Windows Subsystem for Linux (WSL) .
I tried some method to install in Windows 10, but I couldn`t. It may be key to install boost-filesystem.
