### ISSUE TITLE
Use hdf5r rather than h5

### ISSUE THREAD

**Issue by Puriney** [velocyto-team/velocyto.R#42]
## Problem

The dependency `h5` package was no longer available for installation, as noticed here https://github.com/mannau/h5/commit/09382bb2a276d2d81a7a869f6ffd5f95d362f7e2. The author developed the new one `hdf5r`. 

I was wondering if your team can update with that.

## Possible solution suggested by author
See dicussion here:  https://github.com/velocyto-team/velocyto.R/issues/30#issuecomment-429945633

## Env

- R version 3.5.1

**Comment by pkharchenko** [comment]
was addressed by merging pull request #43 (now in the master)
