### ISSUE TITLE
Error in show.velocity.on.embedding.eu

### ISSUE THREAD

**Issue by lambdamoses** [velocyto-team/velocyto.R#44]
I'm trying to plot trajectories like by the end of the Chromaffin differentiation analysis tutorial. Here's my code:

```
show.velocity.on.embedding.eu(emb = clytia@dr$tsne@cell.embeddings, vel = clytia_vel, arrow.scale = 3, show.cell.trajectories = TRUE, nPcs = 50)
```

I did get it to work for `show.velocity.on.embedding.cor`, but for `show.velocity.on.embedding.eu`, I got this error:

```
Error in ncol(em) : object 'em' not found
```

I looked at the source code: https://github.com/velocyto-team/velocyto.R/blob/cb903e02369f8ed413f3062d10f54d2ab507ae46/R/momentum_routines.R#L1337 It referred to `em` in the first line of this function while there's no argument called `em`. Do you actually mean `emb`? That's what I suspect, but please clarify.

**Comment by pkharchenko** [comment]
Thanks. Looks like some lines got swapped in editing … just checked in a fix into the master batch - let me know if you encounter further problems.
