### ISSUE TITLE
Error parsing GTF

### ISSUE THREAD

**Issue by jw156605** [velocyto-team/velocyto.R#5]
I get the following error message when I try to read in smart-seq2 bam files. It seems that velocyto doesn't like the GTF, but I can't figure out why. I obtained the GTF by downloading the hg19 "ucsc genes" track directly from the UCSC table browser. I also tried with the GTF that comes with the 10X Genomics annotation set and got a similar error message. The output is below. Any suggestions would be much appreciated. Thanks!
`library(velocyto.R)
dat <- read.smartseq2.bams(c("scRNA-seq/D0HCF_A01/alignments.sort.bam","scRNA-seq/D0HCF_A02/alignments.sort.bam"),"velocyto_annotations/hg19_genes.gtf",n.cores=1)`
reading gene annotation ... done ( 1461416 genes)
parsing exon information ... Error in `[.data.frame`(x, i, c(10, 11)) : undefined columns selected

**Comment by pkharchenko** [comment]
The current code doesn’t read GTF file, but a refFlat file. You can convert GTF to refFlat using UCSC gtfToGenePred tool:
> gtfToGenePred genes.gtf genes.refFlat


Changing it to read GTF directly should be fairly straightforward, but I haven’t gotten around to that, unfortunately.

Best,
-peter.

**Comment by jw156605** [comment]
Ah, of course. I hadn't noticed that the R tutorial used refFlat rather than genes.gtf. Thanks!
