### ISSUE TITLE
Error in gene.relative.velocity.estimates()

### ISSUE THREAD

**Issue by chent5** [velocyto-team/velocyto.R#65]
Hi,

Thanks a lot for developing velocyto R package. 

I got an error message in gene.relative.velocity.estimates() function. Details are shown below:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/40006284/52254187-42310080-28da-11e9-973d-079c16134444.png">

Could you help me to solve this problem? Thank you so much!

**Comment by chent5** [comment]
I know what's wrong with my code.

**Comment by szhang8** [comment]
Hi Chen, 

I got exactly the same error message. It happened on some of my data but not all of them. Can you share what you have identified in your code and how you fix it? Thanks.

**Comment by chent5** [comment]
Just make sure all the matrices have the same number of rows and the row names should be consistent.
