### ISSUE TITLE
bug in read.smartseq2.bams function

### ISSUE THREAD

**Issue by bioinformaticss** [velocyto-team/velocyto.R#7]
I have mapped reads from smart-seq2 experiment to a bam file for each cell (using mm10). When I  am trying to estimate the necessary matrices using read.smartseq2.bams function and genes.refFlat file from[]( http://pklab.med.harvard.edu/velocyto/chromaffin/bams.tar), I got the following error: 

> Error in dimnames(x) <- dn :
>   length of 'dimnames' [1] not equal to array extent

I believe the error is from the `lengthstats2` function. After estimating `lf`, I found the dimension from the `lf` variable is different from variable `gene`: 

> Browse[4]> dim(genes)
> [1] 24414     8
> Browse[4]> dim(lf)
> [1] 15258     3

This error may also relate to the fact that the dimension of exons is different from that of genes. 
> Browse[4]> dim(exons)
> [1] 40418     4

Any thoughts on this?

**Comment by mliiv** [comment]
Hi,

I am not too experienced but make sure your refFlat file looks like this (this is mm9 downloaded from UCSC table browser), I have 11 columns:
[~]$ head mm9_refSeq_refFlat.txt
Xkr4	NM_001011874	chr1	-	3204562	3661579	3206102	3661429	3	3204562,3411782,3660632,	3207049,3411982,3661579,
Rp1	NM_001195662	chr1	-	4280926	4399322	4283061	4399268	4	4280926,4341990,4342282,4399250,	4283093,4342162,4342918,4399322,
Rp1	NM_011283	chr1	-	4333587	4350395	4334680	4342906	4	4333587,4341990,4342282,4350280,	4340172,4342162,4342918,4350395,

I also had quite a few errors when getting started so best is to run all functions line by line and figure the problem out that way. 

Maybe helps,
-M

**Comment by SamAllon** [comment]
I get this same error when trying to run the Chromaffin differentiation tutorial. Were you able to resolve it?

**Comment by pkharchenko** [comment]
Hi Sam,
 Are you trying to run with the exact bam and gtf files provided in the tutorial? 
-peter.

**Comment by SamAllon** [comment]
I was able to resolve the issue, but I appreciate the quick response, Peter! Some tips for those reading this who are less experienced like me:

1. Allocate sufficient memory (I gave 100g, but that's probably overkill)
2. Use recent version of R (R 3.4.0 works fine)
3. If calling Rscript from the command line, include library(methods) in your script.

**Comment by mahogny** [comment]
Hi! related problem I guess. I am trying to use velocyte.R and I run into a lose end on this page:
http://pklab.med.harvard.edu/velocyto/notebooks/R/chromaffin.nb.html

There is no description of what data/genes.refFlat is nor where to get it from. It's not a commonly used annotation format. So I tried converting a GTF into what I hope is the right format (using gtfToGenePred). And getting

reading gene annotation ... done ( 131195 genes)
parsing exon information ... Error in `[.data.frame`(x, i, c(10, 11)) : undefined columns selected

Some info on which file to use would be really handy!

cheers,
Johan

**Comment by mliiv** [comment]
Hi Johan,

you can get a default refFlat file from the UCSC Table Browser,

Cheers,
Maria

**Comment by slinnarsson** [comment]
To elaborate, go to the [UCSC downloads page](http://hgdownload.soe.ucsc.edu/downloads.html), pick a species and then look for "Annotation database". On that page, download refFlat.txt.gz. 

Direct link to [human](http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/refFlat.txt.gz) and [mouse](http://hgdownload.cse.ucsc.edu/goldenPath/mm10/database/refFlat.txt.gz).

**Comment by pkharchenko** [comment]
Also, you can convert a gif file to refFlat format using UCSD’s gtfToGenePred tool.
We should support GTF though - didn’t get around to that, but we can keep this issue open as an enhancement request.
Best,
-peter.

**Comment by pkharchenko** [comment]
Closing this issue, as read.smartseq2.bams has been deprecated in the new version. The recommended processing for SMART-seq2 (and all other protocols) is to use velocyto.py command line tools for annotation, which will produce a loom file that can be read in on the R side. The chromaffin smart-seq2 example notebook has been updated to show relevant commands.
