### ISSUE TITLE
error in gene.relative.velocity.estimates

### ISSUE THREAD

**Issue by wupeng2** [velocyto-team/velocyto.R#77]
Error information is below. I've use velocity for a long time ,never meet error like this, and I didn't change my command.
> rvel.cd.ref <- gene.relative.velocity.estimates(emat.ref,nmat.ref,deltaT=1,deltaT2 = 1,
+                                                 kCells=2,
+                                                 cell.dist=cell.dist.ref,
+                                                 fit.quantile=fit.quantile,
+                                                 n.cores=24)
matching cells between cell.dist and emat/nmat ... done
calculating cell knn ... done
calculating convolved matrices ... Error in isVirtualExt(exti) : 
  trying to get slot "virtual" from an object of a basic class ("NULL") with no slots

**Comment by xnaer** [comment]
Hi 

I got the same error. How did you solve it?

Bests

Na

**Comment by xnaer** [comment]
Hi @wupeng2 

I got the same error. How did you solve it?

Bests

Na

**Comment by wupeng2** [comment]
sorry for reply too late.i quit R session and rerun, then the problem solved.
