### ISSUE TITLE
Bulk RNA-seq data

### ISSUE THREAD

**Issue by mliiv** [velocyto-team/velocyto.R#8]
Hi, 

How about using velocyto with bulk data - how many replicates are necessary? I see in the circadian paper (SRA025656 dataset you were using) that there is only 1 rep per condition. How to set the parameters for such data? Should I run gene.relative.velocity.estimates with kCells=1 ? Any other parameter differences?

Also - any easy hacks to add labels (cell annotations) to the pca.velocity.plot?

Thanks,
-M

**Comment by mliiv** [comment]
Yes, it was possible to get working with bulk data, you just need to set up the emat and nmat (and smat if you have), depending on which data you have (I used log2 values for rna-seq for example), colors for conditions and then continue with the workflow (functions gene.relative.velocity.estimates, pca.velocity.plot ect).

**Comment by z5ouyang** [comment]
Great! Thanks! I found the following tutorial, in case others have the same problem:
http://pklab.med.harvard.edu/velocyto/notebooks/R/chromaffin2.nb.html
