### ISSUE TITLE
Error in gene.relative.velocity.estimates

### ISSUE THREAD

**Issue by saeedfc** [velocyto-team/velocyto.R#81]
`> rvel.cd <- gene.relative.velocity.estimates(emat0,nmat0,deltaT=1,kCells=20,cell.dist=cell.dist,fit.quantile=fit.quantile)`

calculating cell knn ... done
calculating convolved matrices ... done
fitting gamma coefficients ... done. succesfful fit for 12230 genes
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In parallel::mclapply(sn(rownames(conv.emat.norm)), function(gn) { :
  all scheduled cores encountered errors in user code

Anybody familiar with this error report?

**Comment by saeedfc** [comment]
removed package, reinstalled and restarted R session. Worked!

**Comment by deb0612** [comment]
I had the same error.
I also removed package, reinstalled and restarted R session, but it doesn't work.
> rvel.cd <- gene.relative.velocity.estimates(emat,nmat,deltaT=1,kCells=25,cell.dist=cell.dist,fit.quantile=fit.quantile)
calculating cell knn ... done
calculating convolved matrices ... done
fitting gamma coefficients ... done. succesfful fit for 4261 genes
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In parallel::mclapply(sn(rownames(conv.emat.norm)), function(gn) { :
  all scheduled cores encountered errors in user code
