### ISSUE TITLE
Error with read.smartseq2.bams

### ISSUE THREAD

**Issue by abhaduri** [velocyto-team/velocyto.R#9]
When I run read.smartseq2.bams as noted in the documentation, I get the following error: 

> dat <- read.smartseq2.bams(files,"refFlat.txt",n.cores=40)
reading gene annotation ... done ( 28051 genes)
parsing exon information ... done
reading in 2688 bam files ... done
estimating gene counts ... done
adjusting gene annotation based on expressed regions ... Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric

I am using GRCh38 and downloaded refFlat.txt from the UCSC browser, it has 11 columns. Any insight?

**Comment by pkharchenko** [comment]
Can you please provide more info. A stack trace would be a useful start. But most likely I’d have to debug and look at the variables to see what’s going on.
Thanks,
-peter.

**Comment by abhaduri** [comment]
Let me know what else you may need- I am running this from R and got the following result from traceback: 

> traceback()
4: base::colSums(x, na.rm = na.rm, dims = dims, ...)
3: Matrix::colSums(do.call(rbind, parallel::mclapply(cdl, function(x) {
       ect <- table(c(x$exonstart, x$exonend))
       fect <- rep(0, nrow(exons))
       fect[as.integer(names(ect))] <- ect
       fect
   }, mc.cores = n.cores, mc.preschedule = T)))
2: Matrix::colSums(do.call(rbind, parallel::mclapply(cdl, function(x) {
       ect <- table(c(x$exonstart, x$exonend))
       fect <- rep(0, nrow(exons))
       fect[as.integer(names(ect))] <- ect
       fect
   }, mc.cores = n.cores, mc.preschedule = T)))
1: read.smartseq2.bams(files, "refFlat.txt", n.cores = 40)

**Comment by pkharchenko** [comment]
Is this mouse or human? 
Could you test if using the refFlat file from the chromaffin example gives a similar error?
Does the format of the two files match?
Thanks,
-peter.

**Comment by abhaduri** [comment]
This is human- can you post the refFlat from chromaffin? I got an error when untarring that download, unless I misunderstood the structure of that folder.

**Comment by abhaduri** [comment]
I was able to find the refFlat file- the formats match and when I just use that one (even if it is mouse, figured I could try it) it gives me the same errors. Any thoughts?
